### ISSUE TITLE
server.listen localhost

### ISSUE THREAD

**Issue by smoskwa** [brianvoe/vue-build#11]
Can I suggest you remove 'localhost' from this line:
https://github.com/brianvoe/vue-build/blob/master/bin/dev.js#L92

It currently prevents me from putting vue-build in a docker container and publishing the port to the host

thanks!

**Comment by brianvoe** [comment]
Updated and did a hotfix. v0.43.2 let me know if that works for your setup. Thanks!

**Comment by smoskwa** [comment]
Works perfectly now, thank you

**Comment by brianvoe** [comment]
No problem. If you need help with anything just let me know. Trying to get the word spread about this setup, which we have found to work really well. Any opportunity to help would be much appreciated. Even a something as simple as starring github goes a long way. Thanks!
