### ISSUE TITLE
Docs to fine tune production build

### ISSUE THREAD

**Issue by ptuomaal** [brianvoe/vue-build#14]
vue-build has worked well in my first Vue app. However, I miss general production options that I could easily made to my prod build. Like cache busting, code splitting (at least for vendor and app bundles). I know that these could be done via webpack.config but the reason for choosing vue-build was to avoid all webpack stuff.

So I'm suggesting that you could provide tips for those options in vue-build documentation (maybe in the webpack section) or add those as a option for vue-build prod

**Comment by brianvoe** [comment]
Hey thanks for the feedback. So vue-build was designed not to get rid of using webpack but have all the plugins and base setup of webpack built for you. 

The general idea is at the point in which you need additional plugins or do to code splitting you can have your webpack.config.js file in the root of the project to be able to do merging of things you need in your project into the base webpack config that vue-build provides. The reason for this is every project is unique and needs specific things. So i would say try not to avoid webpack(although it can get frustrating) cause it does provide a lot of powerful things.

That being said I have wanted to make major updates to the docs cause there is a bunch of features that are not described there and ill add some examples of how to do things like code splitting for you as well.

Let me know our thoughts. Thank!

**Comment by ptuomaal** [comment]
doc updates sounds very good. Especially the merging mention currently on the docs with just one example leaves us "backend" devs confused how to introduce your own settings without messing the already provided things. Thx for quick answer



_____________________________

**Comment by brianvoe** [comment]
No problem. Ill be able to get to it tonight and wrap up some things over the weekend. Did you need it right now? If so it might be easier to help you with your current situation

**Comment by ptuomaal** [comment]
no horry from my side

________________________________

**Comment by ptuomaal** [comment]
Have you had a time for the doc updates?

**Comment by brianvoe** [comment]
I have made a bunch of updates to the docs. Trying to polish off some missing things that were in the package but missing from the docs. 

If you need some info on solving your problem i would be more than happy to help in the mean time.

**Comment by ptuomaal** [comment]
My need is to split prod js files to vendor/assets etc file (from node_modules) and to app.js file. And also to add cache busting for dist css and js files.

I have tried to do that stuf by providing my own webpack.config file in root folder like suggested in vue-build documentation but failed to make any difference. Even tries to change webpack logs to more verbose had no effect.

I'm pretty sure that I tried these wrongly but I believe that these actions are needed more or less in any prod builds so it would be nice to see examples for these in vue-build documentation



_____________________________

**Comment by brianvoe** [comment]
Ok so there are two ways you can do code splitting
```
var projectRoot = process.cwd()

// Overriding default base webpack config
module.exports = {
  entry: {
    index: './index.js',
    other: './path/to/thingyouwanttoseperate.js'
  },
  output: {
    filename: '[name].[chunkhash].js',
  },
}
```
This will create two output files in the dist folder index.js and other.js. The [name] is replace with the index and other. The [chunkhash] will create a build specific hash to append to the end of the file name. Thus giving you cache busting https://webpack.js.org/guides/caching/#output-filenames

**Comment by ptuomaal** [comment]
thx, could not get it working in my app but when I created empty project
whit vue-build and added your snippet and it works great. So for some
reason my project webpack.config is ignored etc and that's why I have
struggled with this one.

So thank you for your help, I'll re-create the project for my app

2017-10-14 4:57 GMT+03:00 Brian Voelker <notifications@github.com>:

**Comment by brianvoe** [comment]
So just to clarify the file on the root of your app should be called webpack.config.js
